### ISSUE TITLE
Remove rotations of the molecules before RMSD & RMSF calculation

### ISSUE THREAD

**Issue by BvB93** [BvB93/auto-FOX#12]
Translations of the various molecules can be accounted for by setting the origin of each molecule to its center of mass (option enabled by default).
To do: figure out a way to account for rotations (in an affordable manner).

**Comment by iinfant76** [comment]
Hi Bas, to make the rotations you can use the Kabsch algorithm:
https://en.wikipedia.org/wiki/Kabsch_algorithm

Both the SVD and covariance matrix are libraries of numpy or scipy. I have
used them in the past and are quite easy to use. I also found a repository
where rmsd is calculated with Kabsch: https://github.com/charnley/rmsd

best,
Ivan

**Comment by BvB93** [comment]
Hi Ivan,
Thanks for the suggestion, i'll check it out.

Regards, Bas
